# Generated by Django 4.2.1 on 2024-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="required_amount",
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
