# Generated by Django 4.2.1 on 2024-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_paypal_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recieved", "Recieved"),
                    ("On the way", "On the way"),
                    ("Delivered", "Delivered"),
                ],
                default="Recieved",
                max_length=15,
            ),
        ),
    ]
