# Generated by Django 4.2.1 on 2024-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("PayPal", "PayPal"), ("SSLcommerz", "SSLcommerz")],
                default="PayPal",
                max_length=150,
            ),
        ),
    ]
